Repository orders-squad/orders, pull requests merged in 2018-11, with the labels that each got.

#69 app should give 400 not 500 when receiving bad data
  app/models.py
  app/service.py
  tests/test_orders.py
  tests/test_server.py
Labels: bug

#71 add honcho to requirements.txt
  requirements.txt
Labels: technical debt

#70 align Vagrant file to the one in lab BDD
  Vagrantfile
Labels: technical debt

#86 Restful 1
  Vagrantfile
  app/__init__.py
  app/models.py
  app/service.py
  config.py
  requirements.txt
  tests/test_server.py
Labels: enhancement

#90 Push latest app to bluemix
  Procfile
  app/__init__.py
  manifest.yml
Labels: technical debt

#103 Delete all 1
  app/models.py
  app/service.py
  tests/test_orders.py
  tests/test_server.py
Labels: enhancement

#105 modify swagger doc url from root index to apidoc
  app/service.py
  tests/test_server.py
Labels: enhancement

#107 add honcho start
  Procfile
Labels: enhancement

#109 adding static and feature folder for BDD
  app/static/css/blue_bootstrap.min.css
  app/static/css/darkly_bootstrap.min.css
  app/static/css/flatly_bootstrap.min.css
  app/static/css/slate_bootstrap.min.css
  app/static/images/newapp-icon.png
  app/static/index.html
  app/static/js/jquery-3.1.1.min.js
  app/static/js/rest_api.js
  features/environment.py
  features/order.feature
  features/steps/order_steps.py
Labels: enhancement

#113 Switch to local database
  Vagrantfile
Labels: technical debt
