Repository orders-squad/orders, pull requests merged in 2018-10, with the labels that each got.

#28 add test skeleton code
  requirements.txt
  setup.cfg
  tests/test_model.py
  tests/test_view.py
Labels: technical debt

#27 fix bug: price should be decimal
  app/models.py
  app/view.py
  bootstrap.sh
  config.py
  requirements.txt
Labels: bug

#30 add friendly HTTP status code
  app/view.py
Labels: enhancement

#34 add unittest code for view.py
  app/__init__.py
  app/models.py
  app/view.py
  run.py
  tests/test_model.py
  tests/test_view.py
Labels: enhancement

#36 add travis build info
  .travis.yml
  requirements.txt
Labels: technical debt

#38 add codecov badge
  README.md
Labels: technical debt

#40 Create LICENSE
  LICENSE
Labels: enhancement

#42 refactor code
  .travis.yml
  Vagrantfile
  app/__init__.py
  app/models.py
  app/service.py
  app/view.py
  bootstrap.sh
  config.py
  db/.keep
  db/development.db
  db/test.db
  migrate.py
  requirements.txt
  run.py
  tests/__init__.py
  tests/test_model.py
  tests/test_orders.py
  tests/test_server.py
  tests/test_view.py
Labels: enhancement

#45 update README and update .gitignore
  .gitignore
  README.md
  db/development.db
  db/test.db
Labels: technical debt

#57 Display order
  app/service.py
  tests/test_server.py
Labels: enhancement

#58 add location field in HTTP post response
  app/service.py
Labels: bug

#62 Remove obsolete comment
  app/service.py
Labels: technical debt

#63 update comments and doc string
  app/models.py
Labels: technical debt
